### ISSUE TITLE
Added instructions for Open Liberty on OpenShift 4.2+ / CodeReady Containers

### ISSUE THREAD

**Issue by marcredhat** [IBM/cloud-native-starter#30] opened 2019-11-26 21:54 UTC
Added instructions for Open Liberty on OpenShift 4.2+ / CodeReady Containers at 
https://github.com/marcredhat/crcdemos/blob/master/openliberty/README.adoc

Hope this helps,
Marc

**Comment by Harald-U** [comment] 2019-12-09 08:19
I have planned to work on moving this to CRC sometime this week. Thanks a lot for your input!

**Comment by marcredhat** [comment] 2019-12-09 08:52
Thanks Harald,
I’m testing most of our solutions on CRC/OCP 4.2+, please see youtube playlist at bit.ly/marcredhatplaylist and instructions at bit.ly/marcredhat
Hope this helps,
Marc

**Comment by Harald-U** [comment] 2019-12-10 13:57
Hi Marc, 
is there a reason why you build the container image of authors locally (buildah bud ...), then push it to quay.io, and pull it from there in the yaml file?
I tried a binary build on CRC myself with authors-java-jee and the build failed three times on CRC, seems like this is pushing crc too far ...

**Comment by Harald-U** [comment] 2019-12-18 09:14
I have started to document and script for OpenShift 4.2 / crc now.
It's not completely finished and not linked in the main documentation yet, but if you want to have a look, it starts at https://github.com/IBM/cloud-native-starter/blob/master/documentation/OS4Deployment.md#running-the-cloud-native-starter-on-openshift-42

I am closing this issue, thanks for your input!

**Closed by Harald-U** 2019-12-18 09:14 UTC

**Comment by rdejana** [comment] 2020-03-09 21:14
> Stopping server defaultServer.
> Server defaultServer stop failed. Check server logs for details.
> subprocess exited with status 21
> subprocess exited with status 21
> error: build error: error building at STEP "RUN configure.sh": exit status 21

Sorry to raise this from the dead, but did you ever figure out your issue with the server not stopping when building with buildah?

**Comment by Harald-U** [comment] 2020-03-10 06:59
Ryan, no, I didn't. Instead, I changed the scripts to do a local Docker build, tag, then push into the OpenShift image registry instead of doing a binary build. I wanted results :-)

**Comment by bmarolleau** [comment] 2020-11-27 18:01
Hi , same, raising it from the dead.  I'm experience the same error when trying to build a liberty based image from OpenShift 4.5...  please advise !  (workaround is to build outside and push of course) .
```
STEP 15: RUN configure.sh
subprocess exited with status 21
subprocess exited with status 21
error: build error: error building at STEP "RUN configure.sh": exit status 21
```

**Comment by rdejana** [comment] 2020-11-27 20:25
Please don't as this will be ignored.

**Comment by Harald-U** [comment] 2020-11-27 21:23
Since I am not the developer for OpenShifts binary build process, I can't tell you what "subprocess exited with status 21" really means. But I have an idea: if you look at the descriptiion of the OpenLiberty Iimage on Docker Hub (https://hub.docker.com/_/open-liberty section "Tags") you will find this info:
*...copies in the server.xml that lists the features required by the application, and then uses the configure.sh script to*  **download** *those features from the online repository*
I am pretty sure that the building process on OpenShift will not let you download anything from external into your build.
Sorry if I am of no help for you here.

**Comment by bmarolleau** [comment] 2020-11-28 09:43
Hi @Harald-U ! Thx for the quick reply, which makes sense indeed :)  I'll double check by having a look to this configure.sh script and figure out what's error status 21 means... Certainly related to Liberty "features" download, let's check with the Liberty folks. I'll post something in this thread if I manage to get the root cause.  
Thank you for you time!

**Comment by gasgithub** [comment] 2021-06-08 18:03
Just for others - `error: build error: error building at STEP "RUN configure.sh": exit status 21` 
is completely random, if the during the build repo with features is temporarily inaccessible you will see this.
I had like 5+ successful builds and then suddenly next 3 were failing, and then worked again.
So as in IT, just rerun and hope for the best ;-)
